<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>Resources\app_logo.ico</ApplicationIcon>
    <Version>0.2.3</Version>
    <AssemblyVersion>0.2.3.0</AssemblyVersion>
    <FileVersion>0.2.3.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LanChat.Core\LanChat.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\app_logo.png" />
    <None Update="config.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
